// Desktop smoke for TamagotchIA's local brain: the vendored GUS bridge + pinned llama.cpp
// + a real model + the chat TamagotchIA composes (contract + Context Box, turn).
//
//   gus_smoke <model.gguf> <system.txt> <user.txt> <out-dir>
//
// Writes <out-dir>/text.bin (raw generated bytes) and prints one JSON line of facts.
// Checks that need the TS contract (UTF-8, control tokens, validator) run afterwards in
// tools/gus-smoke-check.ts. This file is TamagotchIA's glue: the bridge itself is untouched.
#include "GUSLlamaBridge.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

static char * slurp(const char * path) {
    FILE * f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char * buf = malloc((size_t)n + 1);
    if (buf && fread(buf, 1, (size_t)n, f) != (size_t)n) { free(buf); buf = NULL; }
    if (buf) buf[n] = '\0';
    fclose(f);
    return buf;
}

static double now_ms(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000.0 + ts.tv_nsec / 1e6;
}

int main(int argc, char ** argv) {
    if (argc != 5) { fprintf(stderr, "usage: %s model.gguf system.txt user.txt out-dir\n", argv[0]); return 2; }
    char * system = slurp(argv[2]);
    char * user = slurp(argv[3]);
    if (!system || !user) { fprintf(stderr, "cannot read inputs\n"); return 2; }
    char err[512] = {0};

    // Cycle 1: load, generate, destroy. Cycle 2: load and destroy again (cleanup must leave a usable process).
    double t0 = now_ms();
    GUSLlamaContext * ctx = gus_llama_create(argv[1], 2048, err, sizeof(err));
    double load_ms = now_ms() - t0;
    if (!ctx) { printf("{\"status\":\"LOAD_FAILED\",\"error\":\"%s\"}\n", err); return 1; }

    GUSChatMessage chat[] = {{"system", system}, {"user", user}};
    GUSSamplingParams sampling = gus_llama_default_chat_sampling();
    sampling.seed = 42;  // fixed so the smoke is repeatable on one machine
    GUSGenerationStats st;
    memset(&st, 0, sizeof(st));
    char * text = gus_llama_generate_chat_sampled(ctx, chat, 2, NULL, 160, &sampling, &st, err, sizeof(err));
    char * desc = gus_llama_model_description(ctx);

    char path[4096];
    snprintf(path, sizeof(path), "%s/text.bin", argv[4]);
    FILE * out = fopen(path, "wb");
    if (out) { if (text) fwrite(text, 1, strlen(text), out); fclose(out); }

    printf("{\"status\":\"%s\",\"load_ms\":%.0f,\"prompt_tokens\":%d,\"generated_tokens\":%d,"
           "\"template_source\":%d,\"stopped_at_eog\":%s,\"prefill_tok_s\":%.1f,\"gen_tok_s\":%.1f,\"model\":\"%s\",\"error\":\"%s\"",
           text ? "OK" : "GENERATE_FAILED", load_ms, st.prompt_tokens, st.generated_tokens, st.template_source,
           st.stopped_at_eog ? "true" : "false",
           st.prefill_ms > 0 ? st.prompt_tokens * 1000.0 / st.prefill_ms : 0.0,
           st.generate_ms > 0 ? st.generated_tokens * 1000.0 / st.generate_ms : 0.0,
           desc ? desc : "", text ? "" : err);
    gus_llama_free_text(desc);
    gus_llama_free_text(text);
    gus_llama_destroy(ctx);

    GUSLlamaContext * again = gus_llama_create(argv[1], 2048, err, sizeof(err));
    printf(",\"reload_after_destroy\":%s}\n", again ? "true" : "false");
    gus_llama_destroy(again);
    free(system);
    free(user);
    return text && again ? 0 : 1;
}
